### ISSUE TITLE
template.css is missing+a slash missing

### ISSUE THREAD

**Issue by ghazal** [coolcat-creations/ccc-mountain#5]
hi,
maybe it is on purpose, but template.css is missing in the distrib.

A slash is missing too on line 26:
`$tplpath = $this->baseurl . 'templates/' . $this->template;`
should be:
`$tplpath = $this->baseurl . '/templates/' . $this->template;`

**Comment by coolcat-creations** [comment]
thank you @ghazal will check it asap

**Comment by ghazal** [comment]
Sorry, I realize I have been a bit blunt. Posted this in a hurry, as always.
1 - nice template and thank you
2 - line 26 in index.php, of course.

**Comment by coolcat-creations** [comment]
Don´t worry :) Thank you for the nice feedback!

**Comment by coolcat-creations** [comment]
Hi! It seems that Joomla automatically adds the slash, but it cleaner if i do it in the template, i just pushed it directly into current staging. Thanks for the report.
