### ISSUE TITLE
Update BS to in error/offline.php

### ISSUE THREAD

**Issue by C-Lodder** [coolcat-creations/ccc-mountain#9]
https://github.com/coolcat-creations/ccc-mountain/blob/master/ccc-mountain/error.php#L137-L138

and:

https://github.com/coolcat-creations/ccc-mountain/blob/master/ccc-mountain/offline.php#L27-L28

**Comment by coolcat-creations** [comment]
Thank you, updated - however there is no error page coming when i have a 404... not sure if it´s a localhost issue, a Joomla 3.8 issue or something else.
